on:
  push:
    tags:
      - 'v*' # Например, v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build binary
        run: |
          pyinstaller --onefile main.py
          mv dist/main dist/ddlog-xray-forwarding  # задаем имя бинарника

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ddlog-xray-forwarding ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: dist/ddlog-xray-forwarding
        env:
          TOKEN: ${{ secrets.FG_PAT }}

      - name: Git tag and push
        env:
          TOKEN: ${{ secrets.FG_PAT }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "bot@example.com"
          git tag v1.0.0
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} --tags
